### ISSUE TITLE
could you please help me how to make a projection management?

### ISSUE THREAD

**Issue by jian8888** [elong0527/esubdemo#4]
I want to make a project management and  downloaded  the esubdemo project  and opened in my R studio environment. 
1.  how can I make to adopt the same folder structure to streamline A&R related works start from scratch? 

2. if I finished the project from development to validation. How can I make a submission for the regulation review? 
I had the same project named esubdemo  in my folder.but got error below:
 library("pkglite")
"esubdemo/" %>%
  collate(file_ectd(), file_auto("inst")) %>%
  pack(output = "r0pkgs.txt")

error below:

"esubdemo/" %>%
+   collate(file_ectd(), file_auto("inst")) %>%
+   pack(output = "r0pkgs.txt")
Error in get_pkg_name(path) : 
  Package root does not have a DESCRIPTION file
In addition: Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="esubdemo/": 系统找不到指定的文件。

**Comment by elong0527** [comment]
> I want to make a project management and downloaded the esubdemo project and opened in my R studio environment.
> 
> 1. how can I make to adopt the same folder structure to streamline A&R related works start from scratch?

It is organized as an R package, you can start from `usethis::create_package" https://usethis.r-lib.org/reference/create_package.html and following Hadley's R package book. https://r-pkgs.org/whole-game.html

If you need to handle multiple projects, I would recommend to create a folder template following 

https://rstudio.github.io/rstudio-extensions/rstudio_project_templates.html

> 2. if I finished the project from development to validation. How can I make a submission for the regulation review?

`"esubdemo"` is a demo file path. You will need to replace to your local working directory.  

@nanxstats , could we clarify this in the book?
 

>    I had the same project named esubdemo  in my folder.but got error below:
>    library("pkglite")
>    "esubdemo/" %>%
>    collate(file_ectd(), file_auto("inst")) %>%
>    pack(output = "r0pkgs.txt")
> 
> error below:
> 
> "esubdemo/" %>%
> 
> * collate(file_ectd(), file_auto("inst")) %>%
> * pack(output = "r0pkgs.txt")
>   Error in get_pkg_name(path) :
>   Package root does not have a DESCRIPTION file
>   In addition: Warning message:
>   In normalizePath(path.expand(path), winslash, mustWork) :
>   path[1]="esubdemo/": 系统找不到指定的文件。

**Comment by nanxstats** [comment]
I think this is clear enough:

https://github.com/elong0527/r4csr/blob/26e2f4137dc639d36ea0c00e19345cd0e9228242/submission-package.Rmd#L38

**Comment by jian8888** [comment]
Hi,yilogn,

可能还是我没理解，R项目文件，与R包的关系，都可以安装发布完成一定的作用。

但我现在是把整个esubdemo项目都拷贝下来到本地目录下，也可以运行，但不知道如何定义路径，来生成递交的文件包。

用这个来打包出错，可能是哪里没理解。file_ectd(),这目录要自定义么？file_auto('inst')这个是在ESUBDEMO下有的：

library("pkglite")

"esubdemo/" %>%
collate(file_ectd(), file_auto("inst")) %>%
pack(output = "r0pkgs.txt")


身边能发布R项目的都没见过，请能解释下最好，非常感谢。

--Jim




-----原始邮件-----
发件人:"yilong zhang" ***@***.***>
发送时间:2021-12-06 23:12:42 (星期一)
收件人: elong0527/esubdemo ***@***.***>
抄送: jian8888 ***@***.***>, Author ***@***.***>
主题: Re: [elong0527/esubdemo] could you please help me how to make a projection management? (Issue #4)






I want to make a project management and downloaded the esubdemo project and opened in my R studio environment.

how can I make to adopt the same folder structure to streamline A&R related works start from scratch?

It is organized as an R package, you can start from `usethis::create_package" https://usethis.r-lib.org/reference/create_package.html and following Hadley's R package book. https://r-pkgs.org/whole-game.html

If you need to handle multiple projects, I would recommend to create a folder template following

https://rstudio.github.io/rstudio-extensions/rstudio_project_templates.html

if I finished the project from development to validation. How can I make a submission for the regulation review?

"esubdemo" is a demo file path. You will need to replace to your local working directory.

@nanxstats , could we clarify this in the book?

I had the same project named esubdemo in my folder.but got error below:
library("pkglite")
"esubdemo/" %>%
collate(file_ectd(), file_auto("inst")) %>%
pack(output = "r0pkgs.txt")

error below:

"esubdemo/" %>%

collate(file_ectd(), file_auto("inst")) %>%
pack(output = "r0pkgs.txt")
Error in get_pkg_name(path) :
Package root does not have a DESCRIPTION file
In addition: Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
path[1]="esubdemo/": 系统找不到指定的文件。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by elong0527** [comment]
If you open from RStudio, you probably can run as current directory `.` where the `DESCRIPTION` file is located. 

```
"." %>%
collate(file_ectd(), file_auto("inst")) %>%
pack(output = "r0pkgs.txt")
```

What's you working directory? 

Please share the output of the code below

```
getwd()
```

```
list.files()
```

**Comment by jian8888** [comment]
Hi Yilong.

thanks a lot.

1.按您的路径.我完成了整个打包下上报测试。

2.打包好的R环境及R包，是不是就是当时生成时的软件环境？这个例子中是指定R包的文件版本日期（2021-08-06）么？

低层的包是开放包（open source packge），还是项目内部包(proprietary R packages)？哪个先安装有关系么？

3.如果要多人一起完成这个PROJECT,是大家都在同一框架下各自完成程序部分，后再整合在一起吧？

我再测试下，到时有些细节再请教，应该可以完成大部分了，谢谢。--Jim

-----原始邮件-----
发件人:"yilong zhang" ***@***.***>
发送时间:2021-12-10 13:03:19 (星期五)
收件人: elong0527/esubdemo ***@***.***>
抄送: jian8888 ***@***.***>, Author ***@***.***>
主题: Re: [elong0527/esubdemo] could you please help me how to make a projection management? (Issue #4)






If you open from RStudio, you probably can run as current directory . where the DESCRIPTION file is located.

"." %>%
collate(file_ectd(), file_auto("inst")) %>%
pack(output = "r0pkgs.txt") 

What's you working directory?

Please share the output of the code below

getwd() 
list.files() 

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
